services:
  - type: web
    name: sistema-colegio
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      bash -c "mkdir -p staticfiles && python manage.py collectstatic --noinput --no-post-process && gunicorn sis_colegio.wsgi:application"
    preDeployCommand: |
      python manage.py migrate --noinput
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: sis_colegio.settings

